module.exports.data ={
    "事件分析": "Event Analysis",
    "指标": "Metrics",
    "自定义指标": "Custom Metrics",
    "未命名图表": "Unnamed Chart",
    "此处可添加说明": "Add Description Here",
    "过去7天": "Past 7 Days",
    "按天": "By Day",
    "保存": "Save",
    "分组": "Grouping",
    "全局过滤": "Global Filters",
    "用户群": "User Group",
    "默认分组": "Default Group",
    "配置位统计": "Configuration Statistics",
    "新建看板": "Create Dashboard",
    "新建看板分组": "Create Dashboard Group",
    "强制刷新数据": "Force Refresh Data",
    "另存为": "Save As",
    "全屏": "Fullscreen",
    "更多": "More",
    "删除看板": "Delete Dashboard",
    "添加图表": "Add Chart",
    "退出全屏": "Exit Fullscreen",
    "还未曾添加图表": "No charts added yet",
    "请填写分组名称": "Please enter a group name",
    "取消": "Cancel",
    "确定": "OK",
    "漏斗分析": "Funnel Analysis",
    "留存分析": "Retention Analysis",
    "用户分析": "User Analysis",
    "路径归因": "Path Attribution",
    "分布分析": "Distribution Analysis",
    "从图库中选择": "Select from Gallery",
    "分析类型": "Analysis Type",
    "搜索图表名": "Search Chart Name",
    "创建图表": "Create Chart",
    "全选": "Select All",
    "图表名称": "Chart Name",
    "图表类型": "Chart Type",
    "最近修改时间": "Last Modified Time",
    "请输入": "Please enter",
    "确定删除看板吗": "Are you sure you want to delete the dashboard?",
    "请填写看板名称": "Please enter a dashboard name",
    "最新刷新时间": "Latest Refresh Time",
    "指标名": "Metric Name",
    "任意事件的总次数": "Total Count of Any Event",
    "计算结果": "Calculation Result",
    "原始数据指标名": "Raw Data Metric Name",
    "请选择": "Please select",
    "条件": "Condition",
    "请选择查询条件": "Please select query conditions",
    "所有用户": "All Users",
    "对比分群": "Compare Segments",
    "仅展示当前账号下有权限查看的数据": "Display only the data that the current account has permission to view",
    "返回": "Return",
    "已保存的图表": "Saved Charts",
    "选择日期": "Select Date"
  }
  module.exports.data2={
    "事件分析": "EventAnalysis",
    "指标": "Metrics",
    "自定义指标": "CustomMetrics",
    "未命名图表": "UnnamedChart",
    "此处可添加说明": "AddDescriptionHere",
    "过去7天": "Past7Days",
    "按天": "ByDay",
    "保存": "Save",
    "分组": "Grouping",
    "全局过滤": "GlobalFilters",
    "用户群": "UserGroup",
    "默认分组": "DefaultGroup",
    "配置位统计": "ConfigurationStatistics",
    "新建看板": "CreateDashboard",
    "新建看板分组": "CreateDashboardGroup",
    "强制刷新数据": "ForceRefreshData",
    "另存为": "SaveAs",
    "全屏": "Fullscreen",
    "更多": "More",
    "删除看板": "DeleteDashboard",
    "添加图表": "AddChart",
    "退出全屏": "ExitFullscreen",
    "还未曾添加图表": "NoChartsAddedYet",
    "请填写分组名称": "PleaseEnterGroupName",
    "取消": "Cancel",
    "确定": "OK",
    "漏斗分析": "FunnelAnalysis",
    "留存分析": "RetentionAnalysis",
    "用户分析": "UserAnalysis",
    "路径归因": "PathAttribution",
    "分布分析": "DistributionAnalysis",
    "从图库中选择": "SelectFromGallery",
    "分析类型": "AnalysisType",
    "搜索图表名": "SearchChartName",
    "创建图表": "CreateChart",
    "全选": "SelectAll",
    "图表名称": "ChartName",
    "图表类型": "ChartType",
    "最近修改时间": "LastModifiedTime",
    "请输入": "PleaseEnter",
    "确定删除看板吗": "AreYouSureToDeleteTheDashboard",
    "请填写看板名称": "PleaseEnterDashboardName",
    "最新刷新时间": "LatestRefreshTime",
    "指标名": "MetricName",
    "任意事件的总次数": "TotalCountOfAnyEvent",
    "计算结果": "CalculationResult",
    "原始数据指标名": "RawDataMetricName",
    "请选择": "PleaseSelect",
    "条件": "Condition",
    "请选择查询条件": "PleaseSelectQueryConditions",
    "所有用户": "AllUsers",
    "对比分群": "CompareSegments",
    "仅展示当前账号下有权限查看的数据": "DisplayOnlyDataWithPermission",
    "返回": "Return",
    "已保存的图表": "SavedCharts",
    "选择日期": "SelectDate"
  }