module.exports.data={
  "图表说明": "Chart Description",
  "添加到看板": "Add to Dashboard",
  "折线图不支持单指标+分组+多群组": "Line chart does not support single metric + grouping + multiple segments",
  "折线图不支持多指标+分组": "Line chart does not support multiple metrics + grouping",
  "状图不支持单指标+分组+多群组": "Bar chart does not support single metric + grouping + multiple segments",
  "柱状图不支持多指标+分组": "Bar chart does not support multiple metrics + grouping",
  "饼图不支持无分组": "Pie chart does not support no grouping",
  "数值不支持分组": "Number value does not support grouping",
  "前5项": "Top 5 Items",
  "前10项": "Top 10 Items",
  "前20项": "Top 20 Items",
  "前50项": "Top 50 Items",
  "昨日": "Yesterday",
  "今日": "Today",
  "上周": "Last Week",
  "本周": "This Week",
  "上月": "Last Month",
  "本月": "This Month",
  "最近7天": "Last 7 Days",
  "过去30天": "Past 30 Days",
  "新建": "Create",
  "查询": "Query",
  "设备账号": "Device Account",
  "账户体系": "Account System",
  "创建漏斗": "Create Funnel",
  "步骗": "Steps",
  "窗口期": "Window Period",
  "天": "Days",
  "初始行为": "Initial Action",
  "后续行为": "Subsequent Action",
  "任意事件": "Any Event",
  "转化": "Conversion",
  "详情": "Details",
  "趋势": "Trend",
  "流失": "Churn",
  "按日": "By Day",
  "次日": "Next Day",
  "7日": "7 Days",
  "14日": "14 Days",
  "30日": "30 Days",
  "按周": "By Week",
  "8周": "8 Weeks",
  "16周": "16 Weeks",
  "24周": "24 Weeks",
  "按月": "By Month",
  "8月": "8 Months",
  "16月": "16 Months",
  "24月": "24 Months",
  "表格": "Table",
  "折线图": "Line Chart",
  "请输入设备账号": "Please enter the device account",
  "事件过滤": "Event Filter",
  "事件": "Event",
  "条件": "Condition",
  "日期": "Date",
  "暂无数据": "No data available",
  "最多展示所选时间范围内最新的1000条行为": "Displaying a maximum of the latest 1000 actions within the selected time range",
  "添加节点": "Add Node",
  "开始分析": "Start Analysis",
  "归因指标": "Attribution Metrics",
  "请选择归因指标": "Please select attribution metrics",
  "的": "of",
  "次数": "count",
  "默认区间": "Default Range",
  "分布": "Distribution",
  "账户体系": "Account System",
  "分群名(ID)": "Segment Name (ID)"
}
module.exports.data2={
  "图表说明": "ChartDesc",
  "添加到看板": "AddToDashboard",
  "折线图不支持单指标+分组+多群组": "LineChartNoSuppSingleMetricGroupMultSegments",
  "折线图不支持多指标+分组": "LineChartNoSuppMultMetricsGrouping",
  "状图不支持单指标+分组+多群组": "BarChartNoSuppSingleMetricGroupMultSegments",
  "柱状图不支持多指标+分组": "BarChartNoSuppMultMetricsGrouping",
  "饼图不支持无分组": "PieChartNoSuppNoGrouping",
  "数值不支持分组": "NumberValueNoSuppGrouping",
  "前5项": "Top5Items",
  "前10项": "Top10Items",
  "前20项": "Top20Items",
  "前50项": "Top50Items",
  "昨日": "Yesterday",
  "今日": "Today",
  "上周": "LastWeek",
  "本周": "ThisWeek",
  "上月": "LastMonth",
  "本月": "ThisMonth",
  "最近7天": "Last7Days",
  "过去30天": "Past30Days",
  "新建": "Create",
  "查询": "Query",
  "设备账号": "DeviceAccount",
  "账户体系": "AccountSystem",
  "创建漏斗": "CreateFunnel",
  "步骗": "Steps",
  "窗口期": "WindowPeriod",
  "天": "Days",
  "初始行为": "InitialAction",
  "后续行为": "SubsequentAction",
  "任意事件": "AnyEvent",
  "转化": "Conversion",
  "详情": "Details",
  "趋势": "Trend",
  "流失": "Churn",
  "按日": "ByDay",
  "次日": "NextDay",
  "7日": "7Days",
  "14日": "14Days",
  "30日": "30Days",
  "按周": "ByWeek",
  "8周": "8Weeks",
  "16周": "16Weeks",
  "24周": "24Weeks",
  "按月": "ByMonth",
  "8月": "8Months",
  "16月": "16Months",
  "24月": "24Months",
  "表格": "Table",
  "折线图": "LineChart",
  "请输入设备账号": "EnterDeviceAccount",
  "事件过滤": "EventFilter",
  "事件": "Event",
  "条件": "Condition",
  "日期": "Date",
  "暂无数据": "NoDataAvailable",
  "最多展示所选时间范围内最新的1000条行为": "ShowMax1000ActionsInSelectedTimeRange",
  "添加节点": "AddNode",
  "开始分析": "StartAnalysis",
  "归因指标": "AttributionMetrics",
  "请选择归因指标": "SelectAttributionMetrics",
  "的": "Of",
  "次数": "Count",
  "默认区间": "DefaultRange",
  "分布": "Distribution",
  "账户体系": "AccountSystem",
  "分群名(ID)": "SegmentNameID"
}