module.exports.data={
  "创建方式": "Creation Method",
  "运行状态": "Running Status",
  "人数": "Number of People",
  "创建人": "Creator",
  "最新计算状态": "Latest Calculation Status",
  "创建时间": "Creation Time",
  "第一次计算时间": "First Calculation Time",
  "更新方式": "Update Method",
  "搜索分群ID": "Search Segment ID",
  "操作": "Operation",
  "新建分群": "Create Segment",
  "设备账号": "Device Account",
  "手机账号": "Mobile Account",
  "资金账号": "Financial Account",
  "规则创建": "Rule-based Creation",
  "结果保存": "Result Saving",
  "ID上传": "ID Upload",
  "外部导入": "External Import",
  "SQL创建": "SQL-based Creation",
  "动态实时": "Dynamic Real-time",
  "正常运行": "Running Normally",
  "已暂停": "Paused",
  "等待计算": "Waiting for Calculation",
  "成功": "Success",
  "失败": "Failure",
  "计算中": "Calculating",
  "且": "AND",
  "或": "OR",
  "更新方式": "Update Method",
  "手动定时": "Manual Scheduled",
  "每天": "Daily",
  "计算": "Calculation",
  "账户体系": "Account System",
  "分群规则": "Segmentation Rules",
  "用户属性满足": "User Attribute Satisfies",
  "用户行为满足": "User Behavior Satisfies",
  "行为序列": "Behavior Sequence",
  "用户群": "User Group",
  "关闭": "Close",
  "返回用户分群": "Return to User Segmentation",
  "分群名": "Segment Name",
  "上传文件": "Upload File",
  "上传txt格式的文档": "Upload a document in txt format",
  "每行代表一个ID": "Each line represents an ID",
  "下载模板": "Download Template"
}
module.exports.data2={
  "创建方式": "CreationMethod",
  "运行状态": "RunningStatus",
  "人数": "NumOfPeople",
  "创建人": "Creator",
  "最新计算状态": "LatestCalculationStatus",
  "创建时间": "CreationTime",
  "第一次计算时间": "FirstCalculationTime",
  "更新方式": "UpdateMethod",
  "搜索分群ID": "SearchSegmentID",
  "操作": "Operation",
  "新建分群": "CreateSegment",
  "设备账号": "DeviceAccount",
  "手机账号": "MobileAccount",
  "资金账号": "FinancialAccount",
  "规则创建": "RuleBasedCreation",
  "结果保存": "ResultSaving",
  "ID上传": "IDUpload",
  "外部导入": "ExternalImport",
  "SQL创建": "SQLBasedCreation",
  "动态实时": "DynamicRealTime",
  "正常运行": "RunningNormally",
  "已暂停": "Paused",
  "等待计算": "WaitingForCalculation",
  "成功": "Success",
  "失败": "Failure",
  "计算中": "Calculating",
  "且": "AND",
  "或": "OR",
  "手动定时": "ManualScheduled",
  "每天": "Daily",
  "计算": "Calculation",
  "账户体系": "AccountSystem",
  "分群规则": "SegmentationRules",
  "用户属性满足": "UserAttributeSatisfies",
  "用户行为满足": "UserBehaviorSatisfies",
  "行为序列": "BehaviorSequence",
  "用户群": "UserGroup",
  "关闭": "Close",
  "返回用户分群": "ReturnToUserSegmentation",
  "分群名": "SegmentName",
  "上传文件": "UploadFile",
  "上传txt格式的文档": "UploadTXTDocument",
  "每行代表一个ID": "EachLineRepresentsAnID",
  "下载模板": "DownloadTemplate"
}