module.exports.data={
  "已上传文件下载": "Download Uploaded File",
  "只保留存量用户": "Keep Only Existing Users",
  "非存量用户将被过滤掉": "Non-existing users will be filtered out",
  "备注": "Note",
  "请输入描述信息": "Please enter a description",
  "提交": "Submit",
  "结果保存修改": "Modify Result Saving",
  "新增": "Add New",
  "编辑": "Edit",
  "元事件": "Meta Event",
  "事件属性": "Event Property",
  "用户属性": "User Property",
  "虚拟事件": "Virtual Event",
  "全部": "All",
  "事件编码": "Event Code",
  "标签筛选": "Tag Filter",
  "请选择": "Please select",
  "事件显示名": "Event Display Name",
  "是否接收": "Receive",
  "是否有数据": "Has Data",
  "最近修改时间": "Last Modified Time",
  "最近修改人": "Last Modified By",
  "备注": "Note",
  "标签": "Tag",
  "是": "Yes",
  "否": "No",
  "创建": "Create",
  "导入": "Import",
  "导出": "Export",
  "标签设置": "Tag Settings",
  "是否预制": "Predefined",
  "属性编码": "Property Code",
  "显示状态": "Display Status",
  "属性显示名": "Property Display Name",
  "数据类型": "Data Type",
  "单位/格式": "Unit/Format",
  "最近修改时间": "Last Modified Time",
  "字典": "Dictionary",
  "修改": "Modify",
  "删除": "Delete",
  "字符串": "String",
  "布尔数值": "Boolean Value",
  "日期时间": "Date Time",
  "列表": "List",
  "主键类型": "Primary Key Type",
  "虚拟事件编码": "Virtual Event Code",
  "虚拟事件显示名": "Virtual Event Display Name",
  "包含事件": "Includes Events",
  "埋点页面": "Tracking Page",
  "埋点事件": "Tracking Event",
  "异常埋点": "Exception Tracking",
  "埋点转换": "Tracking Conversion",
  "应用": "Application",
  "唯一标识": "Unique Identifier",
  "页面名称": "Page Name"
}
module.exports.data2={
  "已上传文件下载": "DownloadUploadedFile",
  "只保留存量用户": "KeepOnlyExistingUsers",
  "非存量用户将被过滤掉": "NonExistingUsersWillBeFilteredOut",
  "备注": "Note",
  "请输入描述信息": "PleaseEnterDescription",
  "提交": "Submit",
  "结果保存修改": "ModifyResultSaving",
  "新增": "AddNew",
  "编辑": "Edit",
  "元事件": "MetaEvent",
  "事件属性": "EventProperty",
  "用户属性": "UserProperty",
  "虚拟事件": "VirtualEvent",
  "全部": "All",
  "事件编码": "EventCode",
  "标签筛选": "TagFilter",
  "请选择": "PleaseSelect",
  "事件显示名": "EventDisplayName",
  "是否接收": "Receive",
  "是否有数据": "HasData",
  "最近修改时间": "LastModifiedTime",
  "最近修改人": "LastModifiedBy",
  "备注": "Note",
  "标签": "Tag",
  "是": "Yes",
  "否": "No",
  "创建": "Create",
  "导入": "Import",
  "导出": "Export",
  "标签设置": "TagSettings",
  "是否预制": "Predefined",
  "属性编码": "PropertyCode",
  "显示状态": "DisplayStatus",
  "属性显示名": "PropertyDisplayName",
  "数据类型": "DataType",
  "单位/格式": "Unit/Format",
  "最近修改时间": "LastModifiedTime",
  "字典": "Dictionary",
  "修改": "Modify",
  "删除": "Delete",
  "字符串": "String",
  "布尔数值": "BooleanValue",
  "日期时间": "DateTime",
  "列表": "List",
  "主键类型": "PrimaryKeyType",
  "虚拟事件编码": "VirtualEventCode",
  "虚拟事件显示名": "VirtualEventDisplayName",
  "包含事件": "IncludesEvents",
  "埋点页面": "TrackingPage",
  "埋点事件": "TrackingEvent",
  "异常埋点": "ExceptionTracking",
  "埋点转换": "TrackingConversion",
  "应用": "Application",
  "唯一标识": "UniqueIdentifier",
  "页面名称": "PageName"
}