module.exports.data={
  "模块列表": "Module List",
  "页面图片": "Page Image",
  "生成方式": "Generation Method",
  "埋点平台/状态": "Tracking Platform/Status",
  "首次埋点的版本": "Version of First Tracking",
  "移动至分组": "Move to Group",
  "修改状态": "Modify Status",
  "可模糊搜索唯一标识和页面名称": "Fuzzy Search for Unique Identifier and Page Name",
  "埋点平台": "Tracking Platform",
  "人工预设": "Manually Predefined",
  "埋点计算": "Tracking Calculation",
  "小程序": "Mini Program",
  "当前状态": "Current Status",
  "已上线": "Online",
  "首次埋点版才": "Only First Tracking Version",
  "已下线": "Offline",
  "首次埋点版本": "First Tracking Version",
  "首次埋点版本模糊查询": "Fuzzy Search for First Tracking Version",
  "批量导入": "Bulk Import",
  "批量导出": "Bulk Export",
  "请输入ID": "Please enter an ID",
  "批量修改": "Bulk Modify",
  "元素名": "Element Name",
  "请输入元素名称": "Please enter an element name",
  "删除": "Delete",
  "空值": "Empty Value",
  "页面": "Page",
  "请输入页面名称": "Please enter a page name",
  "绑定事件": "Bind Event",
  "所属页面（唯一标识）": "Belongs to Page (Unique Identifier)",
  "事件ID": "Event ID",
  "元素名称": "Element Name",
  "所属模块": "Belongs to Module",
  "更多操作": "More Actions",
  "选择应用": "Select Application",
  "注": "Note",
  "请务必选择正确的应用": "Please make sure to select the correct application",
  "点击上传": "Click to Upload",
  "下载excel模板": "Download Excel Template",
  "上传": "Upload",
  "事件详情": "Event Details",
  "事件配置": "Event Configuration",
  "事件编码": "Event Code",
  "事件显示名": "Event Display Name",
  "是否接收": "Receive",
  "是否有数据": "Has Data",
  "自定义属性": "Custom Attribute",
  "属性编码": "Attribute Code"
}
module.exports.data2={
  "模块列表": "ModuleList",
  "页面图片": "PageImage",
  "生成方式": "GenerationMethod",
  "埋点平台/状态": "TrackingPlatform/Status",
  "首次埋点的版本": "VersionOfFirstTracking",
  "移动至分组": "MoveToGroup",
  "修改状态": "ModifyStatus",
  "可模糊搜索唯一标识和页面名称": "FuzzySearchForUniqueIdentifierAndPageName",
  "埋点平台": "TrackingPlatform",
  "人工预设": "ManuallyPredefined",
  "埋点计算": "TrackingCalculation",
  "小程序": "MiniProgram",
  "当前状态": "CurrentStatus",
  "已上线": "Online",
  "首次埋点版才": "OnlyFirstTrackingVersion",
  "已下线": "Offline",
  "首次埋点版本": "FirstTrackingVersion",
  "首次埋点版本模糊查询": "FuzzySearchForFirstTrackingVersion",
  "批量导入": "BulkImport",
  "批量导出": "BulkExport",
  "请输入ID": "PleaseEnterID",
  "批量修改": "BulkModify",
  "元素名": "ElementName",
  "请输入元素名称": "PleaseEnterElementName",
  "删除": "Delete",
  "空值": "EmptyValue",
  "页面": "Page",
  "请输入页面名称": "PleaseEnterPageName",
  "绑定事件": "BindEvent",
  "所属页面（唯一标识）": "BelongsToPage(UniqueIdentifier)",
  "事件ID": "EventID",
  "元素名称": "ElementName",
  "所属模块": "BelongsToModule",
  "更多操作": "MoreActions",
  "选择应用": "SelectApplication",
  "注": "Note",
  "请务必选择正确的应用": "PleaseMakeSureToSelectTheCorrectApplication",
  "点击上传": "ClickToUpload",
  "下载excel模板": "DownloadExcelTemplate",
  "上传": "Upload",
  "事件详情": "EventDetails",
  "事件配置": "EventConfiguration",
  "事件编码": "EventCode",
  "事件显示名": "EventDisplayName",
  "是否接收": "Receive",
  "是否有数据": "HasData",
  "自定义属性": "CustomAttribute",
  "属性编码": "AttributeCode"
}