module.exports.data={
    "属性显示名": "Property Display Name",
    "数据类型": "Data Type",
    "时间范围": "Time Range",
    "埋点记录时间": "Tracking Record Time",
    "埋点记录": "Tracking Record",
    "模糊匹配查询": "Fuzzy Match Query",
    "错误信息": "Error Message",
    "暂无数据": "No Data",
    "选择应用": "Select Application",
    "注": "Note",
    "请务必选择正确的应用": "Please make sure to select the correct application",
    "点击上传": "Click to Upload",
    "下载excel模板": "Download Excel Template",
    "规则KEY": "Rule Key",
    "转换事件": "Convert Event",
    "转换页面编码": "Convert Page Code",
    "转换页面名称": "Convert Page Name",
    "转换模块名称": "Convert Module Name",
    "转换元素名称": "Convert Element Name",
    "模糊查询": "Fuzzy Query",
    "精准匹配": "Exact Match",
    "搜索查询": "Search Query",
    "转换其他属性": "Convert Other Attributes",
    "转换规则": "Convert Rule",
    "分隔符": "Delimiter",
    "顺序": "Order",
    "修改时间": "Modified Time",
    "已加入看板": "Added to Dashboard",
    "类型": "Type",
    "图表名": "Chart Name",
    "规则配置": "Rule Configuration",
    "规则名称": "Rule Name",
    "请输入规则名称": "Please enter a rule name",
    "添加规则": "Add Rule",
    "绑定角色": "Bind Role",
    "请输入角色名称查询": "Please enter a role name to query",
    "已选项": "Selected Options",
    "请输入数据权限规则名称进行查询": "Please enter a data permission rule name to query",
    "应用管理": "Application Management",
    "渠道管理": "Channel Management",
    "应用ID": "Application ID",
    "应用渠道": "Application Channel",
    "应用名称": "Application Name",
    "是否发送": "Whether to Send"
  }
  module.exports.data2={
    "属性显示名": "PropertyDisplayName",
    "数据类型": "DataType",
    "时间范围": "TimeRange",
    "埋点记录时间": "TrackingRecordTime",
    "埋点记录": "TrackingRecord",
    "模糊匹配查询": "FuzzyMatchQuery",
    "错误信息": "ErrorMessage",
    "暂无数据": "NoData",
    "选择应用": "SelectApplication",
    "注": "Note",
    "请务必选择正确的应用": "PleaseMakeSureToSelectTheCorrectApplication",
    "点击上传": "ClickToUpload",
    "下载excel模板": "DownloadExcelTemplate",
    "规则KEY": "RuleKey",
    "转换事件": "ConvertEvent",
    "转换页面编码": "ConvertPageCode",
    "转换页面名称": "ConvertPageName",
    "转换模块名称": "ConvertModuleName",
    "转换元素名称": "ConvertElementName",
    "模糊查询": "FuzzyQuery",
    "精准匹配": "ExactMatch",
    "搜索查询": "SearchQuery",
    "转换其他属性": "ConvertOtherAttributes",
    "转换规则": "ConvertRule",
    "分隔符": "Delimiter",
    "顺序": "Order",
    "修改时间": "ModifiedTime",
    "已加入看板": "AddedToDashboard",
    "类型": "Type",
    "图表名": "ChartName",
    "规则配置": "RuleConfiguration",
    "规则名称": "RuleName",
    "请输入规则名称": "PleaseEnterRuleName",
    "添加规则": "AddRule",
    "绑定角色": "BindRole",
    "请输入角色名称查询": "PleaseEnterRoleNameToQuery",
    "已选项": "SelectedOptions",
    "请输入数据权限规则名称进行查询": "PleaseEnterDataPermissionRuleNameToQuery",
    "应用管理": "ApplicationManagement",
    "渠道管理": "ChannelManagement",
    "应用ID": "ApplicationID",
    "应用渠道": "ApplicationChannel",
    "应用名称": "ApplicationName",
    "是否发送": "WhetherToSend"
  }